In [2]:
# Vertorize your code!!! Vectorization Demo

import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)


In [7]:
# calculate in vector way
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version:" + str(1000*(toc-tic)) +"ms")

# Calculate in 2 for loops
tic = time.time()
for i in range(1000000):
    c += a[i]*b[1]
toc=time.time()

print(c)
print("For loop:" + str(1888*(toc-tic)) + "ms" )

250022.40242005754
Vectorized version:2.2568702697753906ms
374998.79376941227
For loop:392.75341033935547ms


# boardcasting in python; Axis in Array

### Questions: What is the percentage of calorie in each cell. 
<pre>A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.91]])
</pre

<img src='images/1.jpg' width=75%>



In [27]:
import numpy as пр
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.91]])
print (A)

[[ 56.     0.     4.4   68.  ]
 [  1.2  104.    52.     8.  ]
 [  1.8  135.    99.     0.91]]


In [9]:
cal = A.sum(axis=0) # Different from dataframe in Pandas, 0 is doing in column, 1 is doing by row
print(cal)

[ 59.   239.   155.4   76.91]


In [10]:
temp = A.sum(axis=1) # Note it is different from axis = 0
print(temp)

[128.4  165.2  236.71]


In [26]:
percentage = 100 * A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.41503056],
       [ 2.03389831, 43.51464435, 33.46203346, 10.4017683 ],
       [ 3.05084746, 56.48535565, 63.70656371,  1.18320114]])

In [28]:
# Random number
a = np.random.randn(5) 
print(a)
# Note it gives a rank 1 array. 

[-0.31930634  1.91701187  1.95113681 -0.82801128  0.75514818]


In [29]:
print(a.T) # Note it is just same as "a"

[-0.31930634  1.91701187  1.95113681 -0.82801128  0.75514818]


In [32]:
print(np.dot(a,a.T))
print(np.dot(a, a)) 
# there are the same!

8.83967737339359
8.83967737339359


In [35]:
# e.g. 2 

a  = np.random.randn(5,1)
print(a) # Note: there is no comma at the end!

[[ 0.99746038]
 [ 0.00257484]
 [-0.80095161]
 [-0.54111896]
 [-0.88921683]]


In [36]:
print(a.T) # Note: There are 2 bracket, while it is only one for for a.T before. There are different!

[[ 0.99746038  0.00257484 -0.80095161 -0.54111896 -0.88921683]]


In [37]:
# And note, for the dot product, it will have different result
print(np.dot(a, a.T))

[[ 9.94927203e-01  2.56829834e-03 -7.98917491e-01 -5.39744719e-01
  -8.86958552e-01]
 [ 2.56829834e-03  6.62978791e-06 -2.06232019e-03 -1.39329336e-03
  -2.28958879e-03]
 [-7.98917491e-01 -2.06232019e-03  6.41523476e-01  4.33410098e-01
   7.12219647e-01]
 [-5.39744719e-01 -1.39329336e-03  4.33410098e-01  2.92809726e-01
   4.81172082e-01]
 [-8.86958552e-01 -2.28958879e-03  7.12219647e-01  4.81172082e-01
   7.90706567e-01]]


## Don't use Rank 1 array, to avoid confusion 

<img src='images/3.jpg' width=1900>

